name: wp-slm
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=12.1
  - pip:
    - torch>=2.1.0
    - transformers>=4.36.0
    - accelerate>=0.25.0
    - bitsandbytes>=0.41.0
    - peft>=0.7.0
    - trl>=0.7.0
    - datasets>=2.14.0
    - sentencepiece>=0.1.99
    - evaluate>=0.4.0
    - rouge-score>=0.1.2
    - sacrebleu>=2.3.0
    - scikit-learn>=1.3.0
    - pandas>=2.0.0
    - tyro>=0.6.0
    - pydantic>=2.0.0
    - rich>=13.0.0
    - beautifulsoup4>=4.12.0
    - markdownify>=0.11.0
    - readability-lxml>=0.8.1
    - requests>=2.31.0
    - tqdm>=4.66.0
    - numpy>=1.24.0
    - safetensors>=0.4.0
    - vllm>=0.2.0
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
    - sse-starlette>=1.6.0